name: Deploy

on:
  push:
    branches: main

permissions:
  pages: write
  id-token: write

jobs:
  publish-pages:
    uses: jill64/.github/.github/workflows/publish-pages.yml@main
    with:
      output-directory: './demo/build'
